---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - juicefs.io
  resources:
  - cachegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juicefs.io
  resources:
  - cachegroups/finalizers
  verbs:
  - update
- apiGroups:
  - juicefs.io
  resources:
  - cachegroups/status
  verbs:
  - get
  - patch
  - update
