# permissions for end users to edit warmups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: juicefs-cache-group-operator
    app.kubernetes.io/managed-by: kustomize
  name: warmup-editor-role
rules:
- apiGroups:
  - juicefs.io.juicefs.io
  resources:
  - warmups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - juicefs.io.juicefs.io
  resources:
  - warmups/status
  verbs:
  - get
