apiVersion: juicefs.io/v1
kind: CacheGroup
metadata:
  labels:
    app.kubernetes.io/name: juicefs-cache-group-operator
    app.kubernetes.io/managed-by: kustomize
  name: cachegroup-sample
spec:
  secretRef:
    name: juicefs-zxh-test-secret
  cleanCache: false
  updateStrategy:
    type: RollingUpdate
  worker:
    template:
      nodeSelector:
        juicefs.io/cg-worker: "true"
      image: juicedata/mount:ee-5.1.1-1faf43b
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 150m
          memory: 1Gi
      cacheDevices:
        deviceFilter: "sd[a-z]" # 对找到的 device 进行过滤
        deviceMinSize: 1Gi
        deviceMaxSize: 10Gi
    overwrite:
      - nodes:
          - k8s-03
        opts:
        - group-weight=200
