apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
type: Opaque
stringData:
  name: juicefs-xx
  token: xx
  access-key: xx
  secret-key: xx
---
apiVersion: juicefs.io/v1
kind: CacheGroup
metadata:
  name: cachegroup-sample
spec:
  secretRef:
    name: juicefs-secret
  updateStrategy:
    # support：
    # - RollingUpdate: default policy
    # - OnDelete: only manually delete the worker pod, the controller will create a new one
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  worker:
    template:
      nodeSelector:
        juicefs.io/cg-worker: "true"
      image: juicedata/mount:ee-5.1.1-1faf43b
      hostNetwork: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 1
          memory: 1Gi
      opts:
        - cache-dir=/mnt/juicefs:/mnt/juicefs2:/mnt/juicefs3
      volumeMounts:
        - name: cachedir-0
          mountPath: /mnt/juicefs
        - name: cachedir-1
          mountPath: /mnt/juicefs2
        - name: cachedir-2
          mountPath: /mnt/juicefs3
      volumes:
        - name: cachedir-0
          hostPath:
            path: /mnt/juicefs
        - name: cachedir-1
          hostPath:
            path: /dev/sda/juicefs2
        - name: cachedir-2
          persistentVolumeClaim:
            claimName: juicefs-cache-pvc
    overwrite:
      - nodes:
          - k8s-03
        opts:
          - cache-dir=/mnt/juicefs
          - group-weight=50
        volumeMounts:
          - name: cachedir-0
            mountPath: /mnt/juicefs
        volumes:
          - name: cachedir-0
            hostPath:
              path: /mnt/juicefs

