apiVersion: juicefs.io/v1
kind: CacheGroup
metadata:
  labels:
    app.kubernetes.io/name: juicefs-cache-group-operator
    app.kubernetes.io/managed-by: kustomize
  name: cachegroup-sample
spec:
  # TODO(user): Add fields here
