name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: make

    - name: Lint
      run: make lint

    - name: Test
      run: make test

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Set up kind
      uses: helm/kind-action@v1
      with:
        config: test/e2e/config/kind-config.yaml
        cluster_name: e2e

    - name: Run e2e tests
      env:
        KIND_CLUSTER: e2e
        IN_CI: "true"
        JUICEFS_TOKEN: ${{ secrets.JUICEFS_TOKEN }}
      run: make test-e2e

    - name: Setup upterm session
      if: ${{ failure() }}
      timeout-minutes: 60
      uses: lhotari/action-upterm@v1

  success-all-test:
    runs-on: ubuntu-latest
    needs: [ build, e2e ]
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: actions/checkout@v3

      - name: Check Failure
        if: env.WORKFLOW_CONCLUSION == 'failure'
        run: exit 1

      - name: Success
        if: ${{ success() }}
        run: echo "All Done"
